### ISSUE TITLE
Make nearest_mult8 concise

### ISSUE THREAD

**Issue by vitkarpov** [Electrux/feral#2]
I'd like to work on this just to dip my toes into the project.
Here is the current implementation of nearest_mult8 function → https://github.com/Feral-Lang/Feral/blob/9a65fe643918eec9969a9e02aee2d6c756b0e770/src/VM/Memory.cpp#L14

I'd like to shorten it to `sz = (sz + 7) & ~7` and build & run tests along the way.

**Comment by vitkarpov** [comment]
@Electrux hey 👋 Let me know what you think, thanks!

**Comment by Chirag-Khandelwal** [comment]
Oh wow! that seems pretty cool and concise! I'd like to note that tests are still a WIP so please don't rely on them just yet. Most of them may not even work right now (probably due to lack of functions).
But, you can test the memory using any simple test (say `tests/facto_iterate.fer`) and prepending the cmake command with `MEM_PROFILE=true` (such that the command becomes `MEM_PROFILE=true cmake ..`)
That will show the `total allocated bytes` which should hold same values for both before and after modification. 😄

**Comment by Chirag-Khandelwal** [comment]
There is still a lot to be done in the project - from writing test cases to CI, as well as library functions 😅, so I am working on it.
Thanks for helping out ❤️

**Comment by vitkarpov** [comment]
Great! Count this issue on me then 👌

**Comment by Chirag-Khandelwal** [comment]
Awesome! Assigned to you.
Thanks again! 😁
